config/routes.rb
Rails.application.routes.draw do
  root 'products#index', as: 'home'

  get 'about' => 'pages#about'
  
  resources :products do
  	resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :reviews, dependent: :destroy 
	has_one_attached :image, dependent: :destroy 
	validates :title, presence: true, length: {minimum: 5, maximum: 255}
	validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
	validates :description, presence: true
	validates :image, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@about_title = 'About page'
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :require_login, except: [:index, :show]

	def index
		@product_list = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		# render plain: params[:product].inspect
		@product = Product.new(product_params)

		if(@product.save)
			redirect_to @product
		else
			render 'new'
		end
	end

	def update
		@product = Product.find(params[:id])

		if(@product.update(product_params))
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])

		@product.destroy
		redirect_to products_path
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
	end

	private def product_params
		params.require(:product).permit(:title, :description, :image, :price)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :require_login

	def create
		@product = Product.find(params[:product_id])
		@review = @product.reviews.create(review_params)
		redirect_to product_path(@product)
	end

	private def review_params
		params.require(:review).permit(:username, :review_text)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/i18n_helper.rb
module I18nHelper
  def translate(key, options={})
    super(key, options.merge(raise: true))
  rescue I18n::MissingTranslationData
    key
  end
  alias :t :translate
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_nav-bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
    <div class="container">

        <%= link_to "Ruby store", home_path, {:class => 'navbar-brand'} %>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
            &#9776;
        </button>
        
        <div class="collapse navbar-collapse" id="exCollapsingNavbar">
            <ul class="nav navbar-nav">
                <li class="nav-item active">
                    <%= link_to "Home", home_path, {:class => 'nav-link'} %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, {:class => 'nav-link'} %>
                </li>
                <% if signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Add product", new_product_path, {:class => 'nav-link'} %>
                    </li>
                <% end %>
            </ul>

            <% if signed_in? %>
                <div class="nav-item flex-row ml-auto">
                    <%= button_to t("Sign out"), sign_out_path, method: :delete, :class => 'btn btn-danger'%>
                </div>
            <% else %>               
                <div class="nav-item flex-row ml-auto">
                    <%= link_to "Sign in", sign_in_path, :class => 'btn btn-success sign-in-btn' %>
                </div>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RubyStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <%= render partial: '/layouts/nav-bar' %>
  <div class="container">
    <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="about-page">
	<div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="page-caption">
                        <h1 class="page-title">Ruby Store</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card-section">
        <div class="container">
            <div class="card-block bg-white mb30">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="section-title mb-0">
                            <h2>All about Ruby store. We sell everything and everywhere</h2>
                            <p>Our approach is very simple: we help you you to find exctly what you want and deliver it. </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row project-author">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-center">
                	Created by <a href="https://gitlab.com/ardelianvlad/" target="_blank">Vlad Ardelian</a>
        		</div>
           	</div>
        </div>
    </div>
</div>

app/views/products/edit.html.erb
<h3>Edit product:</h3>
<br><div class="text-center">
	<%= image_tag(@product.image) %>
</div> 
<hr>
<%= form_for :product, url: product_path(@product), method: :patch do |f| %>
	<% if @product.errors.any? %>
		<% @product.errors.full_messages.each do |error_message| %>
		<div class="alert alert-danger">
			<%= error_message %>
		</div>
		<% end %>
	<% end %>
	<p>
		Product title:<br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		Product description:<br>
		<%= f.text_area(:description, {:class => 'form-control'}) %>
	</p>

	<p>
		Price:<br>
		<%= f.text_field(:price, {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.file_field :image, {:class => 'form-control'} %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/products/index.html.erb
<br>
<div class="container main-listing">

    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <% @product_list.each do |product| %>   

                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-70">
                            <div class="card-header">
                                <%= image_tag(product.image) %>
                            </div> 
                            <div class="card-body">
                                <h4 class="card-title"><%= product.title %></h4>
                                <h5>$ <%= product.price %></h5>
                                <p class="card-text"><%= product.description %></p>
                            </div>
                            <div class="card-footer text-center">
                                <%= link_to "View", product_path(product), :class => 'btn btn-success' %>
                                <% if signed_in? -%>
                                    <%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Would you like to delete this product?"}, :class => 'btn btn-danger' %>
                                    <%= link_to "Edit", edit_product_path(product), :class => 'btn btn-warning' %>
                                <% end %>
                            </div>
                        </div>
                    </div>

                <% end %>

            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>

app/views/products/new.html.erb
<h3>Create new product:</h3>

<%= form_for :product, url: products_path do |f| %>
	<% if @product.errors.any? %>
		<% @product.errors.full_messages.each do |error_message| %>
		<div class="alert alert-danger">
			<%= error_message %>
		</div>
		<% end %>
	<% end %>
	<p>
		Product title:<br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		Product description:<br>
		<%= f.text_area(:description, {:class => 'form-control'}) %>
	</p>
	<p>
		Price:<br>
		<%= f.text_field(:price, {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.file_field :image, {:class => 'form-control'} %>
	</p>


	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/products/show.html.erb
  <div class="container">

    <div class="row">
      <!-- /.col-lg-3 -->

      <div class="col-lg-12">

        <div class="card mt-4">
          <%= image_tag(@product.image) %> 
          <div class="card-body">
            <h3 class="card-title"><%= @product.title %></h3>
            <h4>$ <%= @product.price %></h4>
            <p class="card-text"><p><%= @product.description %></p></p>

            <% if signed_in? -%>
              <%= link_to "Edit product", edit_product_path(@product), :class => 'btn btn-warning' %>
              <%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Would you like to delete this product?"}, :class => 'btn btn-danger' %>
            <% end %>
            
          </div>
        </div>
        <!-- /.card -->
        <% if signed_in? -%>
          <div class="card card-outline-secondary my-4">
            <div class="card-header">
              Product Reviews
            </div>
            <div class="card-body">
              <% @product.reviews.each do |review| %>

                <p><%= review.review_text %></p>
                <small class="text-muted">Posted by <%= review.username %> on 3/1/17</small>
                <hr>
              <% end %>
              <%= form_for([@product, @product.reviews.build]) do |f| %>
                <p>
                  Review:<br>
                  <%= f.text_area(:review_text, {:class => 'form-control'}) %>
                </p>
                <p>
                  <%= f.submit("Add review", {:class => 'btn btn-success'}) %>
                </p>
              <% end %>
            </div>
          </div>
        <% end %>
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->

    </div>

  </div>

app/views/users/_form.html.erb
<div class="auth-forms">
	<%= form_for @user do |form| %>
		<h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Sign up</h1>

		<div class="text-field">
			<%= form.text_field :email, type: 'email', class: 'form-control', placeholder: 'Email address' %>
		</div>

		<div class="password-field">
		  <%= form.password_field :password, class: 'form-control', placeholder: 'Password'  %>
		</div>

		<div class="submit-field">
	      <%= form.submit 'Sign up', class: 'btn btn-primary btn-block', id: 'sign-up-submit' %>
	    </div>
	<% end %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
	  
	<% if @user && @user.errors.any? %>
		<% @user.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger text-center" role="alert">
		  		<%= msg %>
			</div>
		<% end %>
	<% end %>

    <%= render partial: '/users/form' %>
 
</div>